#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-jsond
Version  : 1.4.0
Release  : 6
URL      : https://pecl.php.net//get/jsond-1.4.0.tgz
Source0  : https://pecl.php.net//get/jsond-1.4.0.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : PHP-3.01
Requires: php-jsond-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
# PHP JSON extension with new Decoder
The php-jsond is a new JSON parser for PHP

%package dev
Summary: dev components for the php-jsond package.
Group: Development
Requires: php-jsond-lib = %{version}-%{release}
Provides: php-jsond-devel = %{version}-%{release}
Requires: php-jsond = %{version}-%{release}

%description dev
dev components for the php-jsond package.


%package lib
Summary: lib components for the php-jsond package.
Group: Libraries

%description lib
lib components for the php-jsond package.


%prep
%setup -q -n jsond-1.4.0
cd %{_builddir}/jsond-1.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/php/ext/jsond/php_jsond.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20190902/jsond.so
